on:
  schedule:
    - cron: '*/3 * * * *'
    - cron: '*/5 * * * *'
    - cron: '*/4 * * * *'
    
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Only for 5 min
        if: github.event.schedule != '*/3 * * * *' && github.event.schedule != '*/4 * * * *'
        run: echo "This job1 step will be skipped on Monday and Wednesday"
      - name: Only for 3 min and 5 min
        if: github.event.schedule != '*/4 * * * *'
        run: echo "This job1 step will be skipped on Monday and Wednesday"
      - name: Every time
        run: echo "This job1 step will always run"
  
  job2:
    runs-on: ubuntu-latest
    steps:
      - name: Only for 3 min
        if: github.event.schedule != '*/4 * * * *' && github.event.schedule != '*/5 * * * *'
        run: echo "This job2 step will be skipped on Monday and Wednesday"
      - name: Only for 4 min
        if: github.event.schedule != '*/5 * * * *' && github.event.schedule != '*/3 * * * *'
        run: echo "This step job2 will be skipped on Monday and Wednesday"
      - name: Every time
        run: echo "This job2 step will always run"
